//! Golden-value suite: the full pinned-config pipeline must reproduce
//! `data/golden/golden.json` (values generated by the Python reference and
//! shared across all language ports).

use std::collections::BTreeMap;
use std::fs;

use serde::Deserialize;

use regime::{carry_rerank_panel, carry_rerank_values, golden_values, run_full_pipeline, CarryRerankInputs};

#[derive(Deserialize)]
struct GoldenFile {
    cases: Vec<GoldenCase>,
}

#[derive(Deserialize)]
struct GoldenCase {
    name: String,
    inputs: serde_json::Value,
    expect: BTreeMap<String, f64>,
    tol: f64,
}

fn load_golden() -> GoldenFile {
    let text = fs::read_to_string("../data/golden/golden.json").expect("golden.json readable");
    serde_json::from_str(&text).expect("golden.json parses")
}

const REQUIRED: [&str; 20] = [
    "hmm_k2_loglik",
    "hmm_k3_loglik",
    "hmm_k3_means",
    "hmm_k3_stds",
    "hmm_k3_transmat",
    "hmm_k3_viterbi_counts",
    "hmm_k3_stationary",
    "hmm_k3_smoothed_t500",
    "hmm_k3_smoothed_t1500",
    "viterbi_accuracy_vs_true",
    "momentum_unfiltered",
    "momentum_filtered",
    "carry_unfiltered",
    "carry_filtered",
    "combined_sharpe",
    "crisis_momentum_return",
    "turnover_momentum",
    "turnover_carry",
    "carry_rerank_positions",
    "carry_rerank_backtest",
];

#[test]
fn golden_file_has_expected_cases() {
    let golden = load_golden();
    let names: Vec<&str> = golden.cases.iter().map(|c| c.name.as_str()).collect();
    assert_eq!(names.len(), 20);
    for required in REQUIRED {
        assert!(names.contains(&required), "missing golden case {required}");
    }
    let by_name: BTreeMap<&str, &GoldenCase> =
        golden.cases.iter().map(|c| (c.name.as_str(), c)).collect();
    for name in ["momentum_unfiltered", "momentum_filtered", "carry_unfiltered", "carry_filtered"] {
        let keys: Vec<&str> = by_name[name].expect.keys().map(String::as_str).collect();
        assert_eq!(
            keys,
            vec!["ann_return", "ann_vol", "calmar", "hit_rate", "max_dd", "sharpe", "worst_month"]
        );
    }
    assert_eq!(by_name["carry_rerank_positions"].tol, 0.0);
}

#[test]
fn golden_values_reproduced() {
    // Recompute every golden case from the full pinned-config pipeline and
    // compare within each case's tolerance (tol = 0 means exact).
    let golden = load_golden();
    let pipe = run_full_pipeline("../data", None, None).expect("pipeline runs");
    let mut computed = golden_values(&pipe);
    let mut checked = 0usize;
    for case in &golden.cases {
        if case.name.starts_with("carry_rerank") {
            // Synthetic panel embedded in `inputs` (API_SPEC 5).
            let inputs: CarryRerankInputs =
                serde_json::from_value(case.inputs.clone()).expect("carry_rerank inputs parse");
            computed.insert(case.name.clone(), carry_rerank_values(&inputs).expect("rerank case runs"));
        }
        let got = computed
            .get(&case.name)
            .unwrap_or_else(|| panic!("case {} not computed", case.name));
        for (key, expect) in &case.expect {
            let value = *got
                .get(key)
                .unwrap_or_else(|| panic!("{}: missing key {key}", case.name));
            if case.tol == 0.0 {
                assert_eq!(value, *expect, "{}:{key} exact mismatch", case.name);
            } else {
                assert!(
                    (value - expect).abs() <= case.tol,
                    "{}:{key} got {value}, want {expect} +/- {}",
                    case.name,
                    case.tol
                );
            }
            checked += 1;
        }
    }
    assert_eq!(checked, 77, "every scalar across the 20 cases must be compared");
}

#[test]
fn carry_rerank_panel_really_reranks() {
    // The bundled differentials never cross; the embedded panel must.
    let golden = load_golden();
    let case = golden.cases.iter().find(|c| c.name == "carry_rerank_positions").unwrap();
    let inputs: CarryRerankInputs = serde_json::from_value(case.inputs.clone()).unwrap();
    let panel = carry_rerank_panel(&inputs).unwrap();
    assert_eq!(panel.rows(), 63);
    assert_eq!(panel.get(9, 0), 0.04);
    assert_eq!(panel.get(10, 0), 0.01);
    assert_eq!(case.expect["pos_day15_asset0"], 1.0); // not yet rebalanced
    assert_eq!(case.expect["pos_day21_asset0"], -1.0); // flipped at day 21
    assert_eq!(case.expect["turnover_day21"], 4.0);
}

#[test]
fn golden_sign_cases() {
    // Semantic checks baked into the golden narrative.
    let golden = load_golden();
    let by_name: BTreeMap<&str, &GoldenCase> =
        golden.cases.iter().map(|c| (c.name.as_str(), c)).collect();
    // momentum loses money in the crisis state (the sign case)
    assert!(by_name["crisis_momentum_return"].expect["ann_return"] < 0.0);
    // the regime filter improves the combined portfolio's Sharpe
    let cs = &by_name["combined_sharpe"].expect;
    assert!(cs["sharpe_filtered"] > cs["sharpe_unfiltered"]);
    // filter improves drawdowns of momentum...
    assert!(by_name["momentum_filtered"].expect["max_dd"] > by_name["momentum_unfiltered"].expect["max_dd"]);
    // ...but costs total return (honest reporting)
    assert!(
        by_name["momentum_filtered"].expect["ann_return"]
            < by_name["momentum_unfiltered"].expect["ann_return"]
    );
    // filtered combined drawdown is shallower too
    assert!(cs["max_dd_filtered"] > cs["max_dd_unfiltered"]);
    // stationary distribution sums to one
    let pis = &by_name["hmm_k3_stationary"].expect;
    let total: f64 = pis.values().sum();
    assert!((total - 1.0).abs() < 1e-8);
    // Viterbi counts sum to the sample size
    let counts = &by_name["hmm_k3_viterbi_counts"].expect;
    let total_days: f64 = counts.values().sum();
    assert_eq!(total_days, 2000.0);
}

#[test]
fn shorter_refit_window_also_runs() {
    // Tests are allowed a faster walk-forward loop: overriding the refit
    // cadence must work and still produce a valid gate (golden values always
    // use the bundled pinned config, checked above).
    let pipe = run_full_pipeline("../data", Some(750), Some(1000)).expect("override pipeline runs");
    for &g in &pipe.gate[..999] {
        assert_eq!(g, 1.0);
    }
    for &g in &pipe.gate {
        assert!((0.0..=1.0).contains(&g));
    }
}
