"""Golden-value suite: the full pinned-config pipeline must reproduce
data/golden/golden.json (values generated by this same implementation and
shared with the other language ports)."""

import numpy as np
import pytest

from regime import golden_cases


def test_golden_file_has_expected_cases(golden):
    names = [c["name"] for c in golden["cases"]]
    assert len(names) == 20
    assert len(set(names)) == 20
    for required in (
        "hmm_k2_loglik",
        "hmm_k3_loglik",
        "hmm_k3_means",
        "hmm_k3_stds",
        "hmm_k3_transmat",
        "hmm_k3_viterbi_counts",
        "hmm_k3_stationary",
        "hmm_k3_smoothed_t500",
        "hmm_k3_smoothed_t1500",
        "viterbi_accuracy_vs_true",
        "momentum_unfiltered",
        "momentum_filtered",
        "carry_unfiltered",
        "carry_filtered",
        "combined_sharpe",
        "crisis_momentum_return",
        "turnover_momentum",
        "turnover_carry",
        "carry_rerank_positions",
        "carry_rerank_backtest",
    ):
        assert required in names
    by_name = {c["name"]: c for c in golden["cases"]}
    for name in ("momentum_unfiltered", "momentum_filtered", "carry_unfiltered", "carry_filtered"):
        assert set(by_name[name]["expect"]) == {
            "ann_return", "ann_vol", "sharpe", "max_dd", "calmar", "hit_rate", "worst_month"
        }
    assert set(by_name["combined_sharpe"]["expect"]) == {
        "sharpe_unfiltered", "sharpe_filtered", "max_dd_unfiltered", "max_dd_filtered"
    }
    assert by_name["carry_rerank_positions"]["tol"] == 0.0
    assert by_name["carry_rerank_positions"]["inputs"]["n_days"] == 63


def test_golden_values_reproduced(golden, pipeline_full):
    """Recompute every golden case from the pipeline and compare within tol."""
    computed = {c["name"]: c for c in golden_cases(pipeline_full)}
    checked = 0
    for case in golden["cases"]:
        got = computed[case["name"]]
        for key, expect in case["expect"].items():
            value = got["expect"][key]
            tol = case["tol"]
            if tol == 0.0:
                assert value == expect, f"{case['name']}:{key} exact mismatch"
            else:
                assert value == pytest.approx(expect, abs=tol), f"{case['name']}:{key}"
            checked += 1
    assert checked == 77  # every scalar across the 20 cases


def test_golden_sign_cases(golden):
    """Semantic checks baked into the golden narrative."""
    by_name = {c["name"]: c for c in golden["cases"]}
    # momentum loses money in the crisis state (the sign case)
    assert by_name["crisis_momentum_return"]["expect"]["ann_return"] < 0.0
    # the regime filter improves the combined portfolio's Sharpe
    cs = by_name["combined_sharpe"]["expect"]
    assert cs["sharpe_filtered"] > cs["sharpe_unfiltered"]
    # filter improves drawdowns of momentum
    assert (
        by_name["momentum_filtered"]["expect"]["max_dd"]
        > by_name["momentum_unfiltered"]["expect"]["max_dd"]
    )
    # ...but costs total return (honest reporting)
    assert (
        by_name["momentum_filtered"]["expect"]["ann_return"]
        < by_name["momentum_unfiltered"]["expect"]["ann_return"]
    )
    # filtered combined drawdown is shallower too
    assert cs["max_dd_filtered"] > cs["max_dd_unfiltered"]
    # the re-ranking panel really re-ranks: the book flips at day 21
    rr = by_name["carry_rerank_positions"]["expect"]
    assert rr["pos_day15_asset0"] == 1.0 and rr["pos_day21_asset0"] == -1.0
    assert rr["turnover_day21"] == 4.0
    # stationary distribution sums to one
    pis = by_name["hmm_k3_stationary"]["expect"]
    assert sum(pis.values()) == pytest.approx(1.0, abs=1e-8)
    # Viterbi counts sum to the sample size
    counts = by_name["hmm_k3_viterbi_counts"]["expect"]
    assert sum(counts.values()) == 2000


def test_shorter_refit_window_also_runs(data_dir):
    """Tests are allowed a faster walk-forward loop: overriding the refit
    cadence must work and still produce a valid gate (golden values always
    use the bundled pinned config, checked above)."""
    from regime import run_full_pipeline

    pipe = run_full_pipeline(data_dir, refit_days=750, train_min_days=1000)
    gate = pipe["gate"]
    assert np.all(gate[:999] == 1.0)
    assert np.all((gate >= 0.0) & (gate <= 1.0))


def test_config_integer_keys_are_strict(data_dir, tmp_path):
    """MAJ-7: the loaders agree — a non-integral n_states (3.0) is rejected."""
    import json
    import shutil

    from regime import load_dataset

    for name in ("market_index.csv", "trend_assets.csv", "fx_carry.csv", "true_states.csv"):
        shutil.copy(data_dir / name, tmp_path / name)
    cfg = json.loads((data_dir / "config.json").read_text())
    cfg["n_states"] = 3.0
    (tmp_path / "config.json").write_text(json.dumps(cfg))
    with pytest.raises(ValueError, match="n_states"):
        load_dataset(tmp_path)
    cfg["n_states"] = 3
    cfg["cost_bps"] = "five"
    (tmp_path / "config.json").write_text(json.dumps(cfg))
    with pytest.raises(ValueError, match="cost_bps"):
        load_dataset(tmp_path)


def test_true_states_range_is_checked(data_dir, tmp_path):
    """MAJ-8: a label outside [0, 2] in true_states.csv is a ValueError at load."""
    import shutil

    from regime import load_dataset

    for name in ("market_index.csv", "trend_assets.csv", "fx_carry.csv", "config.json"):
        shutil.copy(data_dir / name, tmp_path / name)
    lines = (data_dir / "true_states.csv").read_text().splitlines()
    lines[1] = lines[1].rsplit(",", 1)[0] + ",3"
    (tmp_path / "true_states.csv").write_text("\n".join(lines) + "\n")
    with pytest.raises(ValueError, match="true_states"):
        load_dataset(tmp_path)
