"""Golden-value suite: the full pinned-config pipeline must reproduce
data/golden/golden.json (values generated by this same implementation and
shared with the other language ports)."""

import numpy as np
import pytest

from regime import golden_cases


def test_golden_file_has_expected_cases(golden):
    names = [c["name"] for c in golden["cases"]]
    assert len(names) == 18
    assert len(set(names)) == 18
    for required in (
        "hmm_k2_loglik",
        "hmm_k3_loglik",
        "hmm_k3_means",
        "hmm_k3_stds",
        "hmm_k3_transmat",
        "hmm_k3_viterbi_counts",
        "hmm_k3_stationary",
        "hmm_k3_smoothed_t500",
        "hmm_k3_smoothed_t1500",
        "viterbi_accuracy_vs_true",
        "momentum_unfiltered",
        "momentum_filtered",
        "carry_unfiltered",
        "carry_filtered",
        "combined_sharpe",
        "crisis_momentum_return",
        "turnover_momentum",
        "turnover_carry",
    ):
        assert required in names


def test_golden_values_reproduced(golden, pipeline_full):
    """Recompute every golden case from the pipeline and compare within tol."""
    computed = {c["name"]: c for c in golden_cases(pipeline_full)}
    checked = 0
    for case in golden["cases"]:
        got = computed[case["name"]]
        for key, expect in case["expect"].items():
            value = got["expect"][key]
            tol = case["tol"]
            if tol == 0.0:
                assert value == expect, f"{case['name']}:{key} exact mismatch"
            else:
                assert value == pytest.approx(expect, abs=tol), f"{case['name']}:{key}"
            checked += 1
    assert checked >= 40  # many scalar comparisons across the 18 cases


def test_golden_sign_cases(golden):
    """Semantic checks baked into the golden narrative."""
    by_name = {c["name"]: c for c in golden["cases"]}
    # momentum loses money in the crisis state (the sign case)
    assert by_name["crisis_momentum_return"]["expect"]["ann_return"] < 0.0
    # the regime filter improves the combined portfolio's Sharpe
    cs = by_name["combined_sharpe"]["expect"]
    assert cs["sharpe_filtered"] > cs["sharpe_unfiltered"]
    # filter improves drawdowns of momentum
    assert (
        by_name["momentum_filtered"]["expect"]["max_dd"]
        > by_name["momentum_unfiltered"]["expect"]["max_dd"]
    )
    # ...but costs total return (honest reporting)
    assert (
        by_name["momentum_filtered"]["expect"]["ann_return"]
        < by_name["momentum_unfiltered"]["expect"]["ann_return"]
    )
    # stationary distribution sums to one
    pis = by_name["hmm_k3_stationary"]["expect"]
    assert sum(pis.values()) == pytest.approx(1.0, abs=1e-8)
    # Viterbi counts sum to the sample size
    counts = by_name["hmm_k3_viterbi_counts"]["expect"]
    assert sum(counts.values()) == 2000


def test_shorter_refit_window_also_runs(data_dir):
    """Tests are allowed a faster walk-forward loop: overriding the refit
    cadence must work and still produce a valid gate (golden values always
    use the bundled pinned config, checked above)."""
    from regime import run_full_pipeline

    pipe = run_full_pipeline(data_dir, refit_days=750, train_min_days=1000)
    gate = pipe["gate"]
    assert np.all(gate[:999] == 1.0)
    assert np.all((gate >= 0.0) & (gate <= 1.0))
