package com.quant.regime;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import org.junit.Test;

/**
 * Golden-value suite: the full pinned-config pipeline must reproduce
 * data/golden/golden.json (values generated by the Python reference and
 * shared with every language port).
 */
public class GoldenTest {

    /** Recomputes every golden case from one full-pipeline run. */
    private static Map<String, Map<String, Double>> computedCases() {
        Pipeline.Result pipe = TestData.pipeline();
        HmmParams p3 = pipe.hmm3().params();
        Map<String, Map<String, Double>> out = new LinkedHashMap<>();

        out.put("hmm_k2_loglik", Map.of("loglik", pipe.fit2().logLikelihood()));
        out.put("hmm_k3_loglik", Map.of("loglik", pipe.fit3().logLikelihood()));
        Map<String, Double> means = new LinkedHashMap<>();
        Map<String, Double> stds = new LinkedHashMap<>();
        Map<String, Double> trans = new LinkedHashMap<>();
        Map<String, Double> pis = new LinkedHashMap<>();
        for (int k = 0; k < 3; k++) {
            means.put("mean" + k, p3.means[k][0]);
            stds.put("std" + k, Math.sqrt(p3.variances[k][0]));
            pis.put("pi" + k, pipe.stationary3()[k]);
            for (int j = 0; j < 3; j++) {
                trans.put("a" + k + j, p3.transmat[k][j]);
            }
        }
        out.put("hmm_k3_means", means);
        out.put("hmm_k3_stds", stds);
        out.put("hmm_k3_transmat", trans);
        double[] counts = new double[3];
        for (int state : pipe.viterbi3()) {
            counts[state] += 1.0;
        }
        out.put("hmm_k3_viterbi_counts",
                Map.of("count0", counts[0], "count1", counts[1], "count2", counts[2]));
        out.put("hmm_k3_stationary", pis);
        for (int t : new int[] {500, 1500}) {
            Map<String, Double> ps = new LinkedHashMap<>();
            for (int k = 0; k < 3; k++) {
                ps.put("p" + k, pipe.smoothed3()[t][k]);
            }
            out.put("hmm_k3_smoothed_t" + t, ps);
        }
        out.put("viterbi_accuracy_vs_true", Map.of("accuracy", pipe.viterbiAccuracy()));

        for (String name : new String[] {"momentum_unfiltered", "momentum_filtered",
                "carry_unfiltered", "carry_filtered"}) {
            out.put(name, metricEntries(pipe.results().get(name).metrics()));
        }
        out.put("combined_sharpe", Map.of(
                "sharpe_unfiltered", pipe.combinedMetrics().get("unfiltered").sharpe(),
                "sharpe_filtered", pipe.combinedMetrics().get("filtered").sharpe(),
                "max_dd_unfiltered", pipe.combinedMetrics().get("unfiltered").maxDd(),
                "max_dd_filtered", pipe.combinedMetrics().get("filtered").maxDd()));
        out.put("crisis_momentum_return",
                Map.of("ann_return", pipe.crisis().get("momentum_unfiltered")[0].annReturn()));
        out.put("turnover_momentum",
                Map.of("mean_turnover", mean(pipe.results().get("momentum_unfiltered").turnover())));
        out.put("turnover_carry",
                Map.of("mean_turnover", mean(pipe.results().get("carry_unfiltered").turnover())));
        return out;
    }

    /** All seven pinned metrics of one strategy case, keyed as in golden.json. */
    private static Map<String, Double> metricEntries(Backtest.Metrics m) {
        Map<String, Double> out = new LinkedHashMap<>();
        out.put("ann_return", m.annReturn());
        out.put("ann_vol", m.annVol());
        out.put("sharpe", m.sharpe());
        out.put("max_dd", m.maxDd());
        out.put("calmar", m.calmar());
        out.put("hit_rate", m.hitRate());
        out.put("worst_month", m.worstMonth());
        return out;
    }

    /**
     * Builds the pinned re-ranking differential panel from a case's inputs
     * (API_SPEC 5): diff[t] = diffs[k] with k the last index whose
     * switch_days[k] &lt;= t.
     */
    static double[][] carryRerankPanel(Map<?, ?> inputs) {
        int t2 = ((Double) inputs.get("n_days")).intValue();
        int a2 = ((Double) inputs.get("n_assets")).intValue();
        List<?> switchDays = (List<?>) inputs.get("switch_days");
        List<?> diffs = (List<?>) inputs.get("diffs");
        assertEquals(switchDays.size(), diffs.size());
        assertEquals(0.0, (Double) switchDays.get(0), 0.0);
        double[][] panel = new double[t2][a2];
        int k = 0;
        for (int t = 0; t < t2; t++) {
            while (k + 1 < switchDays.size() && ((Double) switchDays.get(k + 1)).intValue() <= t) {
                k++;
            }
            List<?> row = (List<?>) diffs.get(k);
            assertEquals(a2, row.size());
            for (int a = 0; a < a2; a++) {
                panel[t][a] = (Double) row.get(a);
            }
        }
        return panel;
    }

    /** Every carry_rerank_* golden scalar computed by the Java port from inputs. */
    private static Map<String, Double> carryRerankValues(Map<?, ?> inputs) {
        double[][] diffs = carryRerankPanel(inputs);
        double[][] pos = Strategies.carryPositions(diffs,
                ((Double) inputs.get("top_n")).intValue(),
                ((Double) inputs.get("bottom_n")).intValue(),
                ((Double) inputs.get("rebalance_days")).intValue());
        double[][] rets = Strategies.carryTotalReturns(new double[diffs.length][diffs[0].length], diffs);
        Backtest.Result res = Backtest.run(pos, rets, (Double) inputs.get("cost_bps"), null);
        Map<String, Double> out = new LinkedHashMap<>();
        out.put("mean_turnover", mean(res.turnover()));
        out.put("turnover_day21", res.turnover()[21]);
        out.put("turnover_day42", res.turnover()[42]);
        for (int[] ta : new int[][] {{15, 0}, {15, 3}, {21, 0}, {21, 3}, {42, 0}, {42, 3}}) {
            out.put("pos_day" + ta[0] + "_asset" + ta[1], pos[ta[0]][ta[1]]);
        }
        out.put("ann_return", res.metrics().annReturn());
        out.put("sharpe", res.metrics().sharpe());
        out.put("max_dd", res.metrics().maxDd());
        return out;
    }

    private static double mean(double[] x) {
        double s = 0.0;
        for (double v : x) {
            s += v;
        }
        return s / x.length;
    }

    private static Map<?, ?> caseByName(String name) {
        for (Object c : TestData.goldenCases()) {
            Map<?, ?> m = (Map<?, ?>) c;
            if (name.equals(m.get("name"))) {
                return m;
            }
        }
        throw new AssertionError("golden case not found: " + name);
    }

    @Test
    public void goldenFileHasExpectedCases() {
        List<?> cases = TestData.goldenCases();
        assertEquals(20, cases.size());
        Set<String> names = new HashSet<>();
        for (Object c : cases) {
            names.add((String) ((Map<?, ?>) c).get("name"));
        }
        assertEquals(20, names.size());
        for (String required : new String[] {"hmm_k2_loglik", "hmm_k3_loglik", "hmm_k3_means",
                "hmm_k3_stds", "hmm_k3_transmat", "hmm_k3_viterbi_counts", "hmm_k3_stationary",
                "hmm_k3_smoothed_t500", "hmm_k3_smoothed_t1500", "viterbi_accuracy_vs_true",
                "momentum_unfiltered", "momentum_filtered", "carry_unfiltered", "carry_filtered",
                "combined_sharpe", "crisis_momentum_return", "turnover_momentum", "turnover_carry",
                "carry_rerank_positions", "carry_rerank_backtest"}) {
            assertTrue("missing golden case " + required, names.contains(required));
        }
        for (String name : new String[] {"momentum_unfiltered", "momentum_filtered",
                "carry_unfiltered", "carry_filtered"}) {
            Map<?, ?> expect = (Map<?, ?>) caseByName(name).get("expect");
            assertEquals(Set.of("ann_return", "ann_vol", "sharpe", "max_dd", "calmar", "hit_rate",
                    "worst_month"), expect.keySet());
        }
        assertEquals(0.0, (Double) caseByName("carry_rerank_positions").get("tol"), 0.0);
    }

    @Test
    public void carryRerankPanelReallyReranks() {
        // The bundled differentials never cross; the embedded panel must.
        Map<?, ?> rr = caseByName("carry_rerank_positions");
        double[][] panel = carryRerankPanel((Map<?, ?>) rr.get("inputs"));
        assertEquals(63, panel.length);
        assertEquals(0.04, panel[9][0], 0.0);
        assertEquals(0.01, panel[10][0], 0.0);
        assertEquals(1.0, dbl("carry_rerank_positions", "pos_day15_asset0"), 0.0); // not yet rebalanced
        assertEquals(-1.0, dbl("carry_rerank_positions", "pos_day21_asset0"), 0.0); // flipped at day 21
        assertEquals(4.0, dbl("carry_rerank_positions", "turnover_day21"), 0.0);
    }

    @Test
    public void goldenValuesReproduced() {
        // Recompute every golden case from the pipeline and compare within tol.
        Map<String, Map<String, Double>> computed = computedCases();
        int checked = 0;
        for (Object c : TestData.goldenCases()) {
            Map<?, ?> gcase = (Map<?, ?>) c;
            String name = (String) gcase.get("name");
            double tol = (Double) gcase.get("tol");
            Map<?, ?> expect = (Map<?, ?>) gcase.get("expect");
            Map<String, Double> got = name.startsWith("carry_rerank")
                    ? carryRerankValues((Map<?, ?>) gcase.get("inputs"))  // synthetic panel in inputs
                    : computed.get(name);
            assertTrue("case not computed: " + name, got != null);
            for (Map.Entry<?, ?> e : expect.entrySet()) {
                String key = (String) e.getKey();
                double want = (Double) e.getValue();
                Double value = got.get(key);
                assertTrue(name + ":" + key + " missing", value != null);
                if (tol == 0.0) {
                    assertEquals(name + ":" + key + " exact mismatch", want, value, 0.0);
                } else {
                    assertEquals(name + ":" + key, want, value, tol);
                }
                checked++;
            }
        }
        assertEquals("every scalar across the 20 cases", 77, checked);
    }

    @Test
    public void goldenSignCases() {
        // Semantic checks baked into the golden narrative.
        // momentum loses money in the crisis state (the sign case)
        assertTrue(dbl("crisis_momentum_return", "ann_return") < 0.0);
        // the regime filter improves the combined portfolio's Sharpe
        assertTrue(dbl("combined_sharpe", "sharpe_filtered") > dbl("combined_sharpe", "sharpe_unfiltered"));
        // filter improves drawdowns of momentum
        assertTrue(dbl("momentum_filtered", "max_dd") > dbl("momentum_unfiltered", "max_dd"));
        // ...but costs total return (honest reporting)
        assertTrue(dbl("momentum_filtered", "ann_return") < dbl("momentum_unfiltered", "ann_return"));
        // filtered combined drawdown is shallower too
        assertTrue(dbl("combined_sharpe", "max_dd_filtered") > dbl("combined_sharpe", "max_dd_unfiltered"));
        // stationary distribution sums to one
        assertEquals(1.0,
                dbl("hmm_k3_stationary", "pi0") + dbl("hmm_k3_stationary", "pi1")
                        + dbl("hmm_k3_stationary", "pi2"),
                1e-8);
        // Viterbi counts sum to the sample size
        assertEquals(2000.0,
                dbl("hmm_k3_viterbi_counts", "count0") + dbl("hmm_k3_viterbi_counts", "count1")
                        + dbl("hmm_k3_viterbi_counts", "count2"),
                0.0);
    }

    private static double dbl(String caseName, String key) {
        return (Double) ((Map<?, ?>) caseByName(caseName).get("expect")).get(key);
    }

    @Test
    public void shorterRefitWindowAlsoRuns() {
        // Tests are allowed a faster walk-forward loop: overriding the refit
        // cadence must work and still produce a valid gate (golden values
        // always use the bundled pinned config, checked above).
        Pipeline.Result pipe = Pipeline.runFullPipeline(TestData.DATA_DIR, 750, 1000);
        double[] gate = pipe.gate();
        for (int t = 0; t < 999; t++) {
            assertEquals(1.0, gate[t], 0.0);
        }
        for (double g : gate) {
            assertTrue(g >= 0.0 && g <= 1.0);
        }
    }
}
