package com.quant.regime;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import org.junit.Test;

/**
 * Golden-value suite: the full pinned-config pipeline must reproduce
 * data/golden/golden.json (values generated by the Python reference and
 * shared with every language port).
 */
public class GoldenTest {

    /** Recomputes every golden case from one full-pipeline run. */
    private static Map<String, Map<String, Double>> computedCases() {
        Pipeline.Result pipe = TestData.pipeline();
        HmmParams p3 = pipe.hmm3().params();
        Map<String, Map<String, Double>> out = new LinkedHashMap<>();

        out.put("hmm_k2_loglik", Map.of("loglik", pipe.fit2().logLikelihood()));
        out.put("hmm_k3_loglik", Map.of("loglik", pipe.fit3().logLikelihood()));
        Map<String, Double> means = new LinkedHashMap<>();
        Map<String, Double> stds = new LinkedHashMap<>();
        Map<String, Double> trans = new LinkedHashMap<>();
        Map<String, Double> pis = new LinkedHashMap<>();
        for (int k = 0; k < 3; k++) {
            means.put("mean" + k, p3.means[k][0]);
            stds.put("std" + k, Math.sqrt(p3.variances[k][0]));
            pis.put("pi" + k, pipe.stationary3()[k]);
            for (int j = 0; j < 3; j++) {
                trans.put("a" + k + j, p3.transmat[k][j]);
            }
        }
        out.put("hmm_k3_means", means);
        out.put("hmm_k3_stds", stds);
        out.put("hmm_k3_transmat", trans);
        double[] counts = new double[3];
        for (int state : pipe.viterbi3()) {
            counts[state] += 1.0;
        }
        out.put("hmm_k3_viterbi_counts",
                Map.of("count0", counts[0], "count1", counts[1], "count2", counts[2]));
        out.put("hmm_k3_stationary", pis);
        for (int t : new int[] {500, 1500}) {
            Map<String, Double> ps = new LinkedHashMap<>();
            for (int k = 0; k < 3; k++) {
                ps.put("p" + k, pipe.smoothed3()[t][k]);
            }
            out.put("hmm_k3_smoothed_t" + t, ps);
        }
        out.put("viterbi_accuracy_vs_true", Map.of("accuracy", pipe.viterbiAccuracy()));

        for (String name : new String[] {"momentum_unfiltered", "momentum_filtered",
                "carry_unfiltered", "carry_filtered"}) {
            Backtest.Metrics m = pipe.results().get(name).metrics();
            out.put(name, Map.of("ann_return", m.annReturn(), "sharpe", m.sharpe(), "max_dd", m.maxDd()));
        }
        out.put("combined_sharpe", Map.of(
                "sharpe_unfiltered", pipe.combinedMetrics().get("unfiltered").sharpe(),
                "sharpe_filtered", pipe.combinedMetrics().get("filtered").sharpe()));
        out.put("crisis_momentum_return",
                Map.of("ann_return", pipe.crisis().get("momentum_unfiltered")[0].annReturn()));
        out.put("turnover_momentum",
                Map.of("mean_turnover", mean(pipe.results().get("momentum_unfiltered").turnover())));
        out.put("turnover_carry",
                Map.of("mean_turnover", mean(pipe.results().get("carry_unfiltered").turnover())));
        return out;
    }

    private static double mean(double[] x) {
        double s = 0.0;
        for (double v : x) {
            s += v;
        }
        return s / x.length;
    }

    private static Map<?, ?> caseByName(String name) {
        for (Object c : TestData.goldenCases()) {
            Map<?, ?> m = (Map<?, ?>) c;
            if (name.equals(m.get("name"))) {
                return m;
            }
        }
        throw new AssertionError("golden case not found: " + name);
    }

    @Test
    public void goldenFileHasExpectedCases() {
        List<?> cases = TestData.goldenCases();
        assertEquals(18, cases.size());
        Set<String> names = new HashSet<>();
        for (Object c : cases) {
            names.add((String) ((Map<?, ?>) c).get("name"));
        }
        assertEquals(18, names.size());
        for (String required : new String[] {"hmm_k2_loglik", "hmm_k3_loglik", "hmm_k3_means",
                "hmm_k3_stds", "hmm_k3_transmat", "hmm_k3_viterbi_counts", "hmm_k3_stationary",
                "hmm_k3_smoothed_t500", "hmm_k3_smoothed_t1500", "viterbi_accuracy_vs_true",
                "momentum_unfiltered", "momentum_filtered", "carry_unfiltered", "carry_filtered",
                "combined_sharpe", "crisis_momentum_return", "turnover_momentum", "turnover_carry"}) {
            assertTrue("missing golden case " + required, names.contains(required));
        }
    }

    @Test
    public void goldenValuesReproduced() {
        // Recompute every golden case from the pipeline and compare within tol.
        Map<String, Map<String, Double>> computed = computedCases();
        int checked = 0;
        for (Object c : TestData.goldenCases()) {
            Map<?, ?> gcase = (Map<?, ?>) c;
            String name = (String) gcase.get("name");
            double tol = (Double) gcase.get("tol");
            Map<?, ?> expect = (Map<?, ?>) gcase.get("expect");
            Map<String, Double> got = computed.get(name);
            assertTrue("case not computed: " + name, got != null);
            for (Map.Entry<?, ?> e : expect.entrySet()) {
                String key = (String) e.getKey();
                double want = (Double) e.getValue();
                Double value = got.get(key);
                assertTrue(name + ":" + key + " missing", value != null);
                if (tol == 0.0) {
                    assertEquals(name + ":" + key + " exact mismatch", want, value, 0.0);
                } else {
                    assertEquals(name + ":" + key, want, value, tol);
                }
                checked++;
            }
        }
        assertTrue("expected many scalar comparisons", checked >= 40);
    }

    @Test
    public void goldenSignCases() {
        // Semantic checks baked into the golden narrative.
        // momentum loses money in the crisis state (the sign case)
        assertTrue(dbl("crisis_momentum_return", "ann_return") < 0.0);
        // the regime filter improves the combined portfolio's Sharpe
        assertTrue(dbl("combined_sharpe", "sharpe_filtered") > dbl("combined_sharpe", "sharpe_unfiltered"));
        // filter improves drawdowns of momentum
        assertTrue(dbl("momentum_filtered", "max_dd") > dbl("momentum_unfiltered", "max_dd"));
        // ...but costs total return (honest reporting)
        assertTrue(dbl("momentum_filtered", "ann_return") < dbl("momentum_unfiltered", "ann_return"));
        // stationary distribution sums to one
        assertEquals(1.0,
                dbl("hmm_k3_stationary", "pi0") + dbl("hmm_k3_stationary", "pi1")
                        + dbl("hmm_k3_stationary", "pi2"),
                1e-8);
        // Viterbi counts sum to the sample size
        assertEquals(2000.0,
                dbl("hmm_k3_viterbi_counts", "count0") + dbl("hmm_k3_viterbi_counts", "count1")
                        + dbl("hmm_k3_viterbi_counts", "count2"),
                0.0);
    }

    private static double dbl(String caseName, String key) {
        return (Double) ((Map<?, ?>) caseByName(caseName).get("expect")).get(key);
    }

    @Test
    public void shorterRefitWindowAlsoRuns() {
        // Tests are allowed a faster walk-forward loop: overriding the refit
        // cadence must work and still produce a valid gate (golden values
        // always use the bundled pinned config, checked above).
        Pipeline.Result pipe = Pipeline.runFullPipeline(TestData.DATA_DIR, 750, 1000);
        double[] gate = pipe.gate();
        for (int t = 0; t < 999; t++) {
            assertEquals(1.0, gate[t], 0.0);
        }
        for (double g : gate) {
            assertTrue(g >= 0.0 && g <= 1.0);
        }
    }
}
